const MAXIMUM_IMAGES = 9;
const MAX_NOTE_LENGTH = 500;
const WARNING_THRESHOLD = 20;
const MAX_COMMENT_LENGTH = 500;

export { MAXIMUM_IMAGES, MAX_COMMENT_LENGTH, MAX_NOTE_LENGTH, WARNING_THRESHOLD };
