const MAXIMUM_IMAGES = 9;
const MAX_NOTE_LENGTH = 500;
const WARNING_THRESHOLD = 20;
const MAX_COMMENT_LENGTH = 500;
const INITIAL_DISPLAY_COMMENTS = 2;

export {
  INITIAL_DISPLAY_COMMENTS,
  MAXIMUM_IMAGES,
  MAX_COMMENT_LENGTH,
  MAX_NOTE_LENGTH,
  WARNING_THRESHOLD,
};
